Weather_app/urls.py
from django.contrib import admin

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recommender.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recommender/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('recommend/', views.recommend_drink, name='recommend_drink'),
    path('drink/<slug:slug>/', views.drink_detail, name='drink_detail'),
]

recommender/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils.text import slugify


class Drink(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField(default='توضیحی وارد نشده است')
    price = models.IntegerField(default=0)
    image = models.ImageField(upload_to='drinks/', null=True, blank=True)
    temperature_type = models.CharField(
        max_length=10,
        choices=[
            ('hot', 'Hot'),
            ('warm', 'Warm'),
            ('cold', 'Cold')
        ]
    )
    weather_tags = models.TextField(help_text="مثلاً: گرم، سرد، مرطوب")

    # def discounted_price(self):
    #     return (self.price * 0.8)

    def __str__(self):
        return self.name

recommender/views.py
from django.shortcuts import render, get_object_or_404
from .models import Drink
import requests

API_KEY = 'd12112bfc7792cd2628fdc6229ad0250'

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def get_location_by_ip(ip):
    try:
        response = requests.get(f'https://ipapi.co/{ip}/json/')
        data = response.json()
        return data.get('city'), data.get('country_code')
    except Exception as e:
        print("Location error:", e)
        return None, None

def get_temperature(city, country_code, api_key):
    try:
        url = f'https://api.openweathermap.org/data/2.5/weather?q={city},{country_code}&units=metric&appid={api_key}'
        response = requests.get(url)
        data = response.json()
        return data['main']['temp']
    except Exception as e:
        print("Weather error:", e)
        return None

def recommend_drink(request):
    ip = get_client_ip(request)
    city, country_code = get_location_by_ip(ip)

    if not city or not country_code:
        city = 'Gonbad-e Qabus'
        country_code = 'IR'

    temp = get_temperature(city, country_code, API_KEY)

    drinks = []
    if temp is not None:
        if temp > 25:
            drinks = Drink.objects.filter(temperature_type='cold')
        elif 15 <= temp <= 25:
            drinks = Drink.objects.filter(temperature_type='warm')
        else:
            drinks = Drink.objects.filter(temperature_type='hot')


    return render(request, 'recommend/recommend.html', {
        'drinks': drinks,
        'temp': temp,
        'city': city
    })
def drink_detail(request, slug):
    drink = get_object_or_404(Drink, slug=slug)

    if drink.temperature_type == 'cold':
        discounted_price = drink.price * 0.9
    elif drink.temperature_type == 'warm':
        discounted_price = drink.price * 0.8
    elif drink.temperature_type == 'hot':
        discounted_price = drink.price * 0.7

    drink.discounted_price = int(discounted_price)

    return render(request, 'recommend/drink_detail.html', {
        'drink': drink
    })
# def home(request):
#     return render(request, 'home.html')

recommender/templates/recommend/drink_detail.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<h1>{{ drink.name }}</h1>

{% if drink.image %}
    <img src="{{ drink.image.url }}" alt="{{ drink.name }}" width="300">
{% endif %}

{#<p><strong>دما مناسب:</strong> {{ drink.get_temperature_type_display }}</p>#}
<p><strong>قیمت اصلی:</strong> {{ drink.price }}</p>
<p>قیمت با تخفیف: {{ drink.discounted_price }}</p>

<p>{{ drink.description }}</p>

<a href="{% url 'recommend_drink' %}">بازگشت</a>

recommender/templates/recommend/recommend.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<h2>نوشیدنی‌های پیشنهادی:</h2>


{% if temp %}
    <p>شهر شما: {{ city }} — دمای فعلی: {{ temp }} درجه</p>
{% else %}
    <p>نتوانستیم دمای محل شما را دریافت کنیم.</p>
{% endif %}

<ul>

    {% for drink in drinks %}
        <li><a href="{% url 'drink_detail' slug=drink.slug %}">{{ drink.name }}</a></li>
    {% empty %}
        <li>نوشیدنی‌ای پیدا نشد.</li>
    {% endfor %}
</ul>

</body>
</html>